### ISSUE TITLE
CUDA error at /workspace/SAPIEN/3rd_party/sapien-vulkan-2/src/core/buffer.cpp 195: out of memory

### ISSUE THREAD

**Issue by Charlie0257** [haosulab/sapien-vulkan-2#5]
Hi, @fbxiang

How do I specify the GPUs used for Sapien's simulation environment?
In my case, the model of the algorithm is manually loaded onto cuda:0, and then Sapien's simulation environment was automatically loaded onto cuda:3... :(

Thanks for any help :)

**Comment by fbxiang** [comment]
The latest SapienRenderer takes a `device` parameter that you can set to `cuda:0`. You may also want to set `offscreen_only` to `true` since if `cuda:0` cannot render to screen, this parameter may still take priority.

**Comment by Charlie0257** [comment]
Sorry for the late reply. @fbxiang 

In my code, I can not find where can take a device parameter :(
Could you provide detailed instructions or a demo?

Thanks for any suggestions!

**Comment by fbxiang** [comment]
The device argument is passed to `SapienRenderer` class (the first class you create for rendering).
Here is the function signature for `SapienRenderer` constructor.
https://github.com/haosulab/SAPIEN/blob/ab1d9a9fa1428484a918e61185ae9df2beb7cb30/python/py_package/core/pysapien/__init__.pyi#L1644-L1658

**Comment by Charlie0257** [comment]
Thanks for the patient replying! :) @fbxiang
